# Generated by Django 5.0 on 2024-01-04 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=110, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'unite',
                'verbose_name_plural': 'unites',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=60, unique=True)),
                ('prixU', models.IntegerField(default=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productApp.category')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productApp.unite')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
